language: ruby
rvm: 2.2.3
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake
cache: bundler
bundler_args: --without production
