herokuPostgresql:
  image: postgres
  ports:
      - 5432:5432
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  # command: 'bash -c ''bin/rails db:migrate:reset'''
  working_dir: /app/user
  environment:
    PORT: 8080
    # DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    RAILS_ENV: 'development'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
