development:
  host: 'cassandra'
  port: 9042
  keyspace: demo_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: 'cassandra'
  port: 9042
  keyspace: demo_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - 'cass1.demo.biz'
    - 'cass2.demo.biz'
    - 'cass3.demo.biz'
  port: 9042
  keyspace: demo_production
  username: 'myappuser'
  password: 'password1'
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
